// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowEngine.Infrastructure.ProcessEngine.Presistence;

#nullable disable

namespace WorkflowEngine.Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryDBContext))]
    partial class RepositoryDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ActivateOnStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("activate_on_start");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastActivated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activated");

                    b.Property<DateTime?>("LastCompiled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_compiled");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("version");

                    b.Property<string>("VersionBuild")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("version_build");

                    b.HasKey("Id");

                    b.ToTable("t_applications", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.CalculateModuleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalculateActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculate_action_id");

                    b.Property<Guid?>("Input1FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("input1_field_id");

                    b.Property<bool>("Input1IsConstant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("input1_is_constant");

                    b.Property<string>("Input1Value")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("input1_value");

                    b.Property<Guid?>("Input2FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("input2_field_id");

                    b.Property<bool>("Input2IsConstant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("input2_is_constant");

                    b.Property<string>("Input2Value")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("input2_value");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("ResultFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_field_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("CalculateActionId");

                    b.ToTable("t_calculate_module_details", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("locked_by");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ModuleType")
                        .HasColumnType("integer")
                        .HasColumnName("module_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.ProcessModuleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActionModuleType")
                        .HasColumnType("integer")
                        .HasColumnName("action_module_type");

                    b.Property<int?>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<bool>("CommentedFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("commented_flag");

                    b.Property<string>("FailLabel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fail_label");

                    b.Property<string>("LabelName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label_name");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("PassLabel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pass_label");

                    b.Property<Guid>("ProcessModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_module_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("ProcessModuleId");

                    b.ToTable("t_process_module_details", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.CalculateActionModule", b =>
                {
                    b.HasBaseType("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module");

                    b.ToTable("t_calculate_action_modules", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.CompareActionModule", b =>
                {
                    b.HasBaseType("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module");

                    b.Property<Guid?>("Input1FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("input1_field_id");

                    b.Property<bool>("Input1IsConstant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("input1_is_constant");

                    b.Property<string>("Input1Value")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("input1_value");

                    b.Property<Guid?>("Input2FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("input2_field_id");

                    b.Property<bool>("Input2IsConstant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("input2_is_constant");

                    b.Property<string>("Input2Value")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("input2_value");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.ToTable("t_compare_action_modules", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.DatabaseActionModule", b =>
                {
                    b.HasBaseType("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module");

                    b.Property<string>("SqlStatement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_statement");

                    b.ToTable("t_database_action_modules", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.DialogActionModule", b =>
                {
                    b.HasBaseType("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module");

                    b.Property<int>("DialogType")
                        .HasColumnType("integer")
                        .HasColumnName("dialog_type");

                    b.Property<Guid?>("Help1FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("help1_field_id");

                    b.Property<Guid?>("Help2FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("help2_field_id");

                    b.Property<Guid?>("Help3FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("help3_field_id");

                    b.Property<Guid?>("ListModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_module_id");

                    b.Property<string>("MaskCharacter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("*")
                        .HasColumnName("mask_character");

                    b.Property<bool>("MaskInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mask_input");

                    b.Property<Guid?>("MessageFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_field_id");

                    b.Property<Guid?>("OptionsFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("options_field_id");

                    b.Property<Guid?>("ResultFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_field_id");

                    b.ToTable("t_dialog_action_modules", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.FieldModule", b =>
                {
                    b.HasBaseType("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer")
                        .HasColumnName("field_type");

                    b.ToTable("t_field_modules", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.ListModule", b =>
                {
                    b.HasBaseType("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module");

                    b.Property<int?>("MaxRows")
                        .HasColumnType("integer")
                        .HasColumnName("max_rows");

                    b.ToTable("t_list_modules", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.ProcessModule", b =>
                {
                    b.HasBaseType("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.ToTable("t_process_modules", (string)null);
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.CalculateModuleDetail", b =>
                {
                    b.HasOne("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.CalculateActionModule", "CalculateActionModule")
                        .WithMany("Details")
                        .HasForeignKey("CalculateActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculateActionModule");
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.Module", b =>
                {
                    b.HasOne("WorkflowEngine.Domain.ProcessEngine.Entities.Application", "Application")
                        .WithMany("Modules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.ProcessModuleDetail", b =>
                {
                    b.HasOne("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.ProcessModule", "ProcessModule")
                        .WithMany("Details")
                        .HasForeignKey("ProcessModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessModule");
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Application", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.CalculateActionModule", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("WorkflowEngine.Domain.ProcessEngine.Entities.Modules.ProcessModule", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
